// Code generated by Tolulope Joel 😝. EDIT at your own peril.
// versions:
// tolu v25.20.04
// source: tolu.hands

package database

import (
	"database/sql"
	"log"
	"os"
	"time"

	_ "github.com/lib/pq"
)

var (
	db *sql.DB
)

// GetDB returns a singleton database connection
func GetDB() *sql.DB {
	if db != nil {
		return db
	}

	db, err := sql.Open("postgres", os.Getenv("DB_URL"))
	if err != nil {
		log.Fatalf("Failed to connect to database: %v", err)
	}

	db.SetMaxOpenConns(25)
	db.SetMaxIdleConns(25)
	db.SetConnMaxLifetime(5 * time.Minute)

	return db
}

// CloseDB closes the database connection
func CloseDB() {
	if db != nil {
		db.Close()
	}
}
